# fly.toml app configuration file generated for chef2 on 2023-12-05T04:57:00+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chef2"
primary_region = "hkg"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "mysql"
  DB_HOST = "<MYSQL Fly .internal Address>"
  DB_DATABASE = "resta"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/"

[deploy]
  #strategy = "bluegree"
  released_command = "php artisan migrate --force"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
